export const models = [
  {
    id: 1,
    src: "https://6ixelement.club/uploads/pictures/556/thumb_556_IMG_2993%202.JPG",
    nom: " Valentina Pryshyvalko",
    link: "https://6ixelement.club/details.php?id=556",
  },
  {
    id: 2,
    src: "https://6ixelement.club/uploads/pictures/475/thumb_475_alina1.JPG",
    nom: " Alina Uhodnikova",
    link: "https://6ixelement.club/details.php?id=475",
  },
  {
    id: 3,
    src: "https://6ixelement.club/uploads/pictures/465/thumb_465_DSC08577.jpg",
    nom: "India Orhiere",
    link: "https://6ixelement.club/details.php?id=465",
  },
  {id: 4,
  src: "https://6ixelement.club/uploads/pictures/466/thumb_466_image3-2.JPEG",
  nom: "Zaara Ali Zain",
  link: "https://6ixelement.club/details.php?id=466",
},
{  id: 5,
  src: "https://6ixelement.club/uploads/pictures/518/thumb_518_DSC00711.jpg",
  nom: "Pailin Mirault",
  link: "https://6ixelement.club/details.php?id=518",
},
{  id: 6,
  src: "https://6ixelement.club/uploads/pictures/548/thumb_548_IMG_9408.jpg",
  nom: "Eliza Felotin",
  link: "https://6ixelement.club/details.php?id=548",
},
];
